name: Java Card CI

on:
  workflow_run: 
    workflows: ["Semgrep"]
    types:
      - completed

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-multilib libpcsclite1 pcsc-tools wget unzip

      - name: Setup Java (Temurin JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Use JCDK from repository
        run: |
          echo "JC_HOME=$PWD/tools/jcdk" >> $GITHUB_ENV
          echo "PATH=$PWD/tools/jcdk/bin:$PATH" >> $GITHUB_ENV

      - name: Download ECJ
        run: |
          mkdir -p lib
          wget -O lib/ecj.jar https://repo.maven.apache.org/maven2/org/eclipse/jdt/ecj/3.33.0/ecj-3.33.0.jar

      - name: Build CAP
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Run tests
        run: |
          chmod +x scripts/run_tests.sh
          ./scripts/run_tests.sh
  
      - uses: actions/upload-artifact@v7
        with:
          name: insa-cap
          path: build/cap/fr/insa/javacard/insa.cap
  post-release:
    needs: build-and-test

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compute next version tag
        id: next_version
        run: |
          # Récupère tous les tags depuis le dépôt distant
          git fetch --tags

          # Trouve le dernier tag correspondant au format v1.X ou 1.X
          LATEST_TAG=$(git tag -l "v1.*" | sort -V | tail -n 1)

          if [ -z "$LATEST_TAG" ]; then
            # Premier tag si aucun n'existe encore
            NEXT_TAG="v1.0"
          else
            # Extrait le numéro mineur après le dernier point
            PATCH_NUM="${LATEST_TAG##*.}"
            NEXT_NUM=$((PATCH_NUM + 1))
            NEXT_TAG="v1.${NEXT_NUM}"
          fi

          echo "Nouveau tag calculé : $NEXT_TAG"
          echo "tag=$NEXT_TAG" >> "$GITHUB_OUTPUT"
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: insa-cap
          path: build/cap/fr/insa/javacard/

      - name: Release with Assets
        uses: softprops/action-gh-release@v2
        with:
          files: build/cap/fr/insa/javacard/insa.cap
          tag_name: ${{ steps.next_version.outputs.tag }}
          name: Release ${{ steps.next_version.outputs.tag }}
