name: Semgrep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
      actions: read
      
    # container:
    #   # A Docker image with Semgrep installed. Do not change this.
    #   image: semgrep/semgrep
    steps:
      - name : Checkout code
        uses: actions/checkout@v3
      - name: mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --sarif --output results.sarif || true'
      - name: Upload mobsfscan report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
      - name: Verifier les resultats critiques
        run: |
          # Si le fichier de rapport contient "critical" ou "HIGH"
          if grep -q "CRITICAL" rapport-securite.json; then
            echo "::error::Vulnérabilité critique détectée, blocage du workflow."
            exit 1
          fi
